# Generated by Django 4.0.10 on 2023-09-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSISD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.PositiveIntegerField()),
                ('MNO', models.CharField(max_length=255)),
                ('country_code', models.PositiveIntegerField()),
                ('subscriber_number', models.PositiveIntegerField()),
                ('country_identifier', models.CharField(max_length=255)),
            ],
        ),
    ]
