# Generated by Django 4.0.10 on 2023-09-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSISD',
            fields=[
                ('msisdn', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('MNO', models.CharField(max_length=255)),
                ('country_code', models.PositiveBigIntegerField()),
                ('subscriber_number', models.PositiveBigIntegerField()),
                ('country_identifier', models.CharField(max_length=255)),
            ],
        ),
    ]
